---

version: '3'
services:
  aai-mock:
    image: registry.gitlab.ics.muni.cz:443/perun-proxy-aai/containers/docker-gdi:latest
    container_name: ls-aai-mock
    volumes:
      - "./configuration/aai-mock:/etc/lsaai-mock"
    ports:
      - '8080:8080'
    networks:
      - lsaaimock
      - my-app-network
  aai-db:
    image: mysql/mysql-server:latest
    container_name: ls-aai-db
    environment:
      MYSQL_ROOT_PASSWORD: 'aaiPass'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'aai'
      MYSQL_USER: 'aai'
      MYSQL_PASSWORD: 'aaiPass'
    volumes:
      - "./scripts/aai-mock.sql:/docker-entrypoint-initdb.d/1.sql"
    # remove this to disable persistent storage
      - "./mysql://var/lib/mysql"
    ports:
      - '3306:3306'
    networks:
      - lsaaimock
      - my-app-network
# Uncomment if you need to write visas into the broker - this is the storage for the broker
  #broker-db:
  #  image: mysql/mysql-server:latest
  #  container_name: ls-broker-db
  #  environment:
  #    MYSQL_ROOT_PASSWORD: 'rootPass'
  #    MYSQL_ROOT_HOST: '%'
  #    MYSQL_DATABASE: 'broker'
  #    MYSQL_USER: 'brokerUser'
  #    MYSQL_PASSWORD: 'brokerPass'
  #  volumes:
  #    - "./scripts/ga4gh-broker.sql:/docker-entrypoint-initdb.d/1.sql"
  #  # remove this to disable persistent storage
  #    - "./mysql://var/lib/mysql"
  #  ports:
  #    - '3307:3306'
  #  networks:
  #    - lsaaimock

networks:
  lsaaimock:
  my-app-network:
    external: true
